version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
    command: mongod

  backend:
    build: ./
    hostname: backend
    volumes:
      - ./:/app/
      - .env.docker:/app/.env
    ports:
      - 3002:3002
    entrypoint: /bin/sh
    command: -c "sleep 5 && npm run start:dev"
    depends_on:
      - mongodb
