const CONSTANTS = {} as any;

CONSTANTS.DATABASE_CONNECTION = 'DATABASE_CONNECTION';
CONSTANTS.MODEL_USER = 'MODEL_USER';
CONSTANTS.MODEL_ROLE = 'MODEL_ROLE';
CONSTANTS.MODEL_ENTITY = 'MODEL_ENTITY';

export default CONSTANTS;
